#!/usr/bin/env node
/**
 * PostToolUse hook for Write / Edit: force CRLF line endings.
 *
 * WHY THIS EXISTS. This repo is CRLF throughout (740 of 785 tracked text files;
 * `core.autocrlf=true` normalises to LF inside git, so only the working tree is
 * affected). Claude Code writes LF by default, so new files and sometimes edited
 * ones came back LF. The result is a diff where every line looks changed, which
 * buries the real change and has to be cleaned up by hand. Remembering the rule
 * did not work - the harness executes this hook, so it cannot be forgotten.
 *
 * THE ONE EXCEPTION is `prisma/migrations/`. Those files are generated by
 * `prisma migrate` with LF, they are checksummed in `_prisma_migrations`, and
 * they are never hand-edited. Rewriting them would be both pointless and a
 * drift risk - see the migration-drift note in CLAUDE.md.
 *
 * Binary-safe: a file containing a NUL byte is left alone, so an image or font
 * written through a tool is never mangled.
 *
 * Silent by design. A hook that reports on every edit is noise; this one either
 * fixes the file or does nothing.
 */
import { readFileSync, writeFileSync, statSync } from "node:fs";

try {
  const payload = JSON.parse(readFileSync(0, "utf8") || "{}");
  const path =
    payload?.tool_response?.filePath ?? payload?.tool_input?.file_path ?? "";

  if (!path) process.exit(0);

  // The sanctioned LF island. Matched on either separator so it holds on
  // Windows paths too.
  if (/prisma[\\/]migrations[\\/]/i.test(path)) process.exit(0);

  if (!statSync(path, { throwIfNoEntry: false })?.isFile()) process.exit(0);

  const buf = readFileSync(path);

  // Binary guard.
  if (buf.includes(0)) process.exit(0);

  const text = buf.toString("utf8");

  // Collapse to LF first, then expand - going straight from LF to CRLF would
  // turn an existing CRLF into CRCRLF.
  const normalised = text.replace(/\r\n/g, "\n").replace(/\n/g, "\r\n");

  if (normalised !== text) {
    writeFileSync(path, normalised, "utf8");
  }
} catch {
  // A formatting hook that crashes must never disrupt the turn.
}
process.exit(0);
