import { readdirSync } from "node:fs";
import { join, posix } from "node:path";
import { describe, it, expect } from "vitest";
import {
  PUBLIC_ASSET_ALLOWLIST,
  hasFileExtension,
  isPublicAssetPath,
  isUnservableAssetPath,
} from "./publicAssets";

const PUBLIC_DIR = join(process.cwd(), "public");

function walk(dir: string, base = ""): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const url = posix.join(base, entry.name);
    return entry.isDirectory()
      ? walk(join(dir, entry.name), url)
      : [`/${url}`];
  });
}

describe("public asset allowlist", () => {
  // THE GUARD THAT MATTERS. The proxy 404s every dotted path that is not
  // allowlisted here, so a file added to public/ and forgotten in
  // publicAssets.ts would silently stop being served. Same contract as
  // appRoutes.test.ts walking the app directory for routing.pathnames.
  it("serves every file that actually exists in public/", () => {
    const missing = walk(PUBLIC_DIR).filter((path) => !isPublicAssetPath(path));

    expect(
      missing,
      `These files exist in public/ but the proxy would 404 them. Add them to PUBLIC_ASSET_FILES (or cover their directory with a prefix) in src/lib/security/publicAssets.ts:\n${missing.join("\n")}`,
    ).toEqual([]);
  });

  it("does not allowlist files that were deleted from public/", () => {
    const onDisk = new Set(walk(PUBLIC_DIR));
    // Only the root-level entries are reconciled: the rest are generated by
    // src/app (icon.svg, manifest.webmanifest, ...) and never live on disk.
    const generated = new Set([
      "/icon.svg",
      "/apple-icon.png",
      "/manifest.webmanifest",
      "/sitemap.xml",
      "/robots.txt",
    ]);
    const stale = [...PUBLIC_ASSET_ALLOWLIST.files].filter(
      (path) => !generated.has(path) && !onDisk.has(path),
    );

    expect(stale, `Allowlisted but no longer in public/: ${stale.join(", ")}`).toEqual([]);
  });
});

describe("hasFileExtension", () => {
  it("looks at the last segment only", () => {
    // A dotted DIRECTORY with an ordinary final segment is not a file request -
    // this is what keeps ACME challenges working.
    expect(hasFileExtension("/.well-known/acme-challenge/xyz")).toBe(false);
    expect(hasFileExtension("/en/products/some-slug")).toBe(false);
    expect(hasFileExtension("/backup.zip")).toBe(true);
    expect(hasFileExtension("/static/js/main.chunk.js.map")).toBe(true);
  });
});

describe("isUnservableAssetPath", () => {
  it("404s the scanner probes that used to render a page", () => {
    // Every one of these was recorded against the staging error log.
    for (const path of [
      "/backup.zip",
      "/marketverseapp.com.zip",
      "/favicon.png",
      "/favicon.ico.png",
      "/main.c6d13be3ea6fc9cb.js",
      "/app.js.map",
      "/static/js/main.chunk.js.map",
      "/wp-content/uploads/2023/08/logo-gold.png",
      "/assets/favicon-aOK6_042.ico",
      "/images/01.jpg",
      "/news5c/assets/images/logo.svg",
      "/vite.config.js",
      "/webpack.mix.js",
      "/.pnp.js",
      "/api/config/sendgrid.yaml",
    ]) {
      expect(isUnservableAssetPath(path), path).toBe(true);
    }
  });

  it("keeps serving this app's own files", () => {
    for (const path of [
      "/favicon.ico",
      "/email-logo.png",
      "/header-stars-cosmos.png",
      "/pdf.worker.min.mjs",
      "/fonts/Geist-Regular.ttf",
      "/brand/stripe-logo-dark.png",
      "/icon.svg",
      "/apple-icon.png",
      "/manifest.webmanifest",
      "/sitemap.xml",
      "/robots.txt",
      "/.well-known/acme-challenge/token",
      "/.well-known/security.txt",
    ]) {
      expect(isUnservableAssetPath(path), path).toBe(false);
    }
  });

  it("leaves ordinary pages and API routes alone", () => {
    for (const path of [
      "/",
      "/en",
      "/sr/proizvodi/neki-slug",
      "/en/dashboard/orders/abc",
      "/api/webhooks/stripe",
      "/api/products",
    ]) {
      expect(isUnservableAssetPath(path), path).toBe(false);
    }
  });
});
