/**
 * Which dotted (file-shaped) URLs this app actually serves.
 *
 * WHY THIS EXISTS. `isScannerPath` in ./scannerPaths.ts answers probes by
 * matching known-bad shapes, but it never saw most of them: the middleware
 * matcher used to skip every path ending in a static extension, so
 * `/backup.zip`, `/favicon.png`, `/main.c6d13be3ea6fc9cb.js`,
 * `/wp-content/uploads/*.png` and `/app.js.map` bypassed middleware entirely,
 * fell through to the `[locale]/[...rest]` catch-all, RENDERED A PAGE, woke
 * Neon and logged an error apiece. Roughly 40 of the 107 errors recorded on
 * staging between 06.09 and 12.09 arrived this way.
 *
 * Blocklists cannot win that race - the next scanner invents a new filename.
 * So the matcher now lets dotted paths through and this module decides: a path
 * whose last segment carries an extension is served only if it is one of ours,
 * and everything else is answered 404 before any render.
 *
 * That inverts the risk: a new file in `public/` that nobody adds here would
 * 404. `publicAssets.test.ts` walks `public/` on disk and fails CI in exactly
 * that case, the same way `appRoutes.test.ts` guards `routing.pathnames`.
 *
 * Safe for real routes because no route of this app has a dot in its last
 * segment: `slugify` strips every character outside `[a-z0-9-]`, so no slug
 * this app has ever minted contains one.
 */

/**
 * Directories served wholesale.
 *
 * `.well-known` is NOT a `public/` directory - it is a real standard (ACME
 * challenges, security.txt) and blocking it would break certificate issuance.
 * It is listed for the same reason scannerPaths.ts refuses to match it.
 */
const PUBLIC_ASSET_PREFIXES = ["/fonts/", "/brand/", "/.well-known/"];

/**
 * Exact files: everything at the root of `public/`, plus the dotted URLs Next
 * generates from `src/app` (`icon.svg`, `apple-icon.png`, `manifest.ts`,
 * `sitemap.ts`, `robots.ts`).
 */
const PUBLIC_ASSET_FILES = new Set([
  // public/
  "/favicon.ico",
  "/email-header-bg.png",
  "/email-logo.png",
  "/header-stars-cosmos.png",
  "/header-stars-dark.png",
  "/header-stars-light.png",
  "/pdf.worker.min.mjs",
  // generated by src/app
  "/icon.svg",
  "/apple-icon.png",
  "/manifest.webmanifest",
  "/sitemap.xml",
  "/robots.txt",
]);

/** Exported for publicAssets.test.ts, which reconciles it against `public/`. */
export const PUBLIC_ASSET_ALLOWLIST = {
  files: PUBLIC_ASSET_FILES,
  prefixes: PUBLIC_ASSET_PREFIXES,
} as const;

/**
 * True when the last path segment carries a file extension - the signal that a
 * URL names a file rather than a page. Anchored to the LAST segment on purpose:
 * `/.well-known/acme-challenge/xyz` names a directory with a dot and a
 * perfectly ordinary final segment.
 */
export function hasFileExtension(pathname: string): boolean {
  const lastSegment = pathname.slice(pathname.lastIndexOf("/") + 1);
  return lastSegment.includes(".");
}

export function isPublicAssetPath(pathname: string): boolean {
  if (PUBLIC_ASSET_FILES.has(pathname)) return true;
  return PUBLIC_ASSET_PREFIXES.some(
    (prefix) => pathname.startsWith(prefix) || pathname === prefix.slice(0, -1),
  );
}

/**
 * A file-shaped URL this app has nothing to serve for. The proxy answers these
 * 404 immediately - no render, no database wake-up, no error log.
 */
export function isUnservableAssetPath(pathname: string): boolean {
  return hasFileExtension(pathname) && !isPublicAssetPath(pathname);
}
